window.AppData = {
  STORAGE_KEYS: {
    v3: "dictationPlayground_v3",
    v2: "dictationPlayground_v2",
  },
  SCORE_RULES: {
    base: 10,
    streak3Bonus: 2,
    streak5Bonus: 5,
    replayPenalty: [0, 1, 2],
  },
  MAX_REPLAY: 2,
  SESSION_SIZE: 10,
  PLAYBACK_MS: 2200,
  AVATARS: ["🐰", "🐻", "🐥", "🐱", "🦊", "🐼"],
  LEVELS: [
    { score: 0, title: "🌱 새싹" },
    { score: 80, title: "✨ 반짝" },
    { score: 180, title: "⭐ 별님" },
    { score: 320, title: "🌈 무지개" },
  ],
  QUESTIONS: [
    { id: 1, word: "나무", category: "자연", difficulty: 1 },
    { id: 2, word: "바다", category: "자연", difficulty: 1 },
    { id: 3, word: "강아지", category: "동물", difficulty: 1 },
    { id: 4, word: "학교", category: "생활", difficulty: 1 },
    { id: 5, word: "별빛", category: "자연", difficulty: 1 },
    { id: 6, word: "토끼", category: "동물", difficulty: 1 },
    { id: 7, word: "우산", category: "생활", difficulty: 1 },
    { id: 8, word: "연필", category: "학교", difficulty: 1 },
    { id: 9, word: "달님", category: "자연", difficulty: 2 },
    { id: 10, word: "사과", category: "음식", difficulty: 1 },
    { id: 11, word: "무지개", category: "자연", difficulty: 2 },
    { id: 12, word: "비행기", category: "탈것", difficulty: 2 },
    { id: 13, word: "호랑이", category: "동물", difficulty: 2 },
    { id: 14, word: "도서관", category: "학교", difficulty: 2 },
  ],
  ACHIEVEMENTS: [
    { id: "first_correct", name: "첫 정답", desc: "처음으로 정답 맞히기" },
    { id: "streak3", name: "3연속 성공", desc: "연속 정답 3회 달성" },
    { id: "solve10", name: "10문제 돌파", desc: "누적 10문제 풀기" },
    { id: "accuracy80", name: "정답률 장인", desc: "정답률 80% 이상 달성" },
    { id: "no_replay", name: "집중의 달인", desc: "다시듣기 없이 정답 맞히기" },
    { id: "champion", name: "오늘의 챔피언", desc: "랭킹 1위 달성" },
  ],
  MISSION_DEFS: [
    { id: "mission_streak3", text: "3문제 연속 정답", target: 3, type: "streak" },
    { id: "mission_solve5", text: "오늘 5문제 풀기", target: 5, type: "solvedToday" },
    { id: "mission_no_replay2", text: "다시듣기 없이 2문제 정답", target: 2, type: "noReplayCorrectToday" },
  ],
  PRAISE: [
    "정말 멋진 집중력이야!",
    "오늘도 반짝반짝 성장 중!",
    "차근차근 도전하는 모습이 최고야!",
  ],
};
